<a href="https://colab.research.google.com/github/dunomi/zw/blob/master/z5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Import bibliotek i stworzenie listy i array

In [1]:
import numpy as np
import timeit

ar=np.random.random(30)
li=np.random.random(30).tolist()

print(ar)
print(li)

[0.72324484 0.18757981 0.34381211 0.50114577 0.77685311 0.69499034
 0.85648596 0.11523493 0.50402773 0.47177549 0.22142808 0.01659578
 0.25958621 0.89850283 0.78961946 0.63215576 0.60971078 0.63749695
 0.12195634 0.91271292 0.69494143 0.53999869 0.79426435 0.56703421
 0.30267191 0.7946131  0.29988351 0.18892851 0.00851339 0.04432158]
[0.554235952037113, 0.9453261153414342, 0.049291379611517305, 0.759872684598693, 0.20899173629861756, 0.1081567053167104, 0.7766096491578284, 0.9741095561890756, 0.744506279287081, 0.20128185959509182, 0.7285101552981567, 0.40019788077931195, 0.3978164567669018, 0.2983806720046883, 0.19407134544252924, 0.8716465115337861, 0.3523753283926434, 0.5367549357223943, 0.9311275327626484, 0.030437791216690657, 0.6735481072158349, 0.6022974503355321, 0.23482679236996695, 0.12968963609739947, 0.9704862596748616, 0.3422352891448651, 0.4385751242644571, 0.035437966024483014, 0.7755710601584876, 0.6182979589329415]


Zdefiniowanie funckji dla listy i array

In [2]:
 def ArrayOperations():
   ar_min=ar.min()
   ar_max=ar.max()
   ar_sum=ar.sum()
   ar_prod=ar.prod()
   ar_mean=ar.mean()
   ar_std=ar.std()
   ar_var=ar.var()
   return {'min':ar_min,'max':ar_max,'sum':ar_sum,'prod':ar_prod,'mean':ar_mean,'std':ar_std,'var':ar_var}

 def ListOperations():
   li_min=min(li)
   li_max=max(li)
   li_sum=sum(li)
   li_prod=1
   for i in range(len(li)):
     li_prod*=li[i]
   li_mean=sum(li)/len(li)
   li_var_n=0
   for i in range(len(li)):
     li_var_n+=(li[i]-li_mean)**2
   li_var=li_var_n/len(li)
   li_std=li_var**(1/2) 
   return {'min':li_min,'max':li_max,'sum':li_sum,'prod':li_prod,'mean':li_mean,'std':li_std,'var':li_var}

print(ArrayOperations())
print(ListOperations())

{'min': 0.008513391447039553, 'max': 0.9127129162242857, 'sum': 14.51008586895152, 'prod': 4.764238532606084e-15, 'mean': 0.48366952896505067, 'std': 0.2810874862281977, 'var': 0.07901017491408721}
{'min': 0.030437791216690657, 'max': 0.9741095561890756, 'sum': 14.884666171571745, 'prod': 4.826171197536928e-14, 'mean': 0.49615553905239146, 'std': 0.30212080635281224, 'var': 0.09127698163127348}


In [3]:
t_ar = timeit.timeit(ArrayOperations, number=1000)
t_li = timeit.timeit(ListOperations, number=1000)

print("Czas funkcji Array:",t_ar)
print("Czas funkcji List:",t_li)
if t_ar>t_li: print("Wniosek: Operacje na Liście w tym przypadku szybsze niż na Array")
else: print("Wniosek: Operacje na Array w tym przypadku szybsze niż na Liście")

Czas funkcji Array: 0.06755636200000481
Czas funkcji List: 0.008348449000010305
Wniosek: Operacje na Liście w tym przypadku szybsze niż na Array


Sprawdzenie mniej elementarnych obliczeń

In [4]:
#podniesienie do kwadratu każdego elementu
def x(): [i**2 for i in li] 
def y(): ar**2

t_ar = timeit.timeit(y, number=1000)
t_li = timeit.timeit(x, number=1000)

print("Czas funkcji Array:",t_ar)
print("Czas funkcji List:",t_li)
if t_ar>t_li: print("Wniosek: Operacje na Liście w tym przypadku szybsze niż na Array")
else: print("Wniosek: Operacje na Array w tym przypadku szybsze niż na Liście")

Czas funkcji Array: 0.0020753750000039872
Czas funkcji List: 0.005303569999995261
Wniosek: Operacje na Array w tym przypadku szybsze niż na Liście


Wybrane sposoby oracy z tablicami zdefiniowanymi w pakiecie numpy

In [25]:
x=np.random.random(100)
x=x.reshape(4,5,5) #zmiana kształu na array zawierjącego 4 główne listy które zawierają po 5 pięcio elementowych list
print(x)

[[[0.98478647 0.99084552 0.40068918 0.41136602 0.75407423]
  [0.07186905 0.31055138 0.44553644 0.85924538 0.62232779]
  [0.38318291 0.77880269 0.20524689 0.59920339 0.02988483]
  [0.21338933 0.46564084 0.06168967 0.9936828  0.85046713]
  [0.84203167 0.43025603 0.12981235 0.98644219 0.88616767]]

 [[0.02607126 0.09373261 0.26845799 0.71311758 0.73121298]
  [0.06459564 0.12054514 0.05956822 0.85461539 0.92077199]
  [0.41316598 0.49427592 0.13093732 0.44933546 0.88541291]
  [0.70356256 0.85172319 0.00231029 0.95245856 0.12289152]
  [0.23411679 0.7876928  0.61866079 0.39558482 0.76334173]]

 [[0.30754688 0.88478236 0.8946762  0.50043781 0.03700988]
  [0.15382232 0.02917476 0.7022826  0.36134593 0.82104094]
  [0.82659265 0.53605408 0.71055174 0.31651509 0.90590999]
  [0.39283888 0.60325198 0.42084243 0.71923674 0.41422721]
  [0.08965478 0.59361763 0.98437312 0.85163676 0.66215221]]

 [[0.72997496 0.34663355 0.7811646  0.74008296 0.45068479]
  [0.08224268 0.9542565  0.1610935  0.27256222 0.3

In [31]:
print("Liczba wymiarów:",x.ndim)
print("Rozmiar tablicy:",x.shape)
print("Liczba elementów:",x.size)
print("Typ elementów:",x.dtype)
print("Rozmiar elementu w bajtach:",x.itemsize)

Liczba wymiarów: 3
Rozmiar tablicy: (4, 5, 5)
Liczba elementów: 100
Type elementów: float64
Rozmiar elementu w bajtach: 8
