<a href="https://colab.research.google.com/github/dunomi/zw/blob/master/z5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Import bibliotek i stworzenie listy i array

In [98]:
import numpy as np
import timeit

ar=np.random.random(30)
li=np.random.random(30).tolist()

print(ar)
print(li)

[0.17764092 0.77845461 0.65992612 0.07166589 0.19273275 0.83593278
 0.63008445 0.37922633 0.23459667 0.3518804  0.58231853 0.53123212
 0.07167164 0.12372736 0.11360184 0.8457429  0.63908151 0.17072715
 0.05941828 0.17396436 0.91411279 0.59133944 0.70704604 0.10274481
 0.68632799 0.41955758 0.39793261 0.29278679 0.7413277  0.85736279]
[0.26911357763922295, 0.26447773783094153, 0.3158300902035951, 0.3312240751360048, 0.46047981840170915, 0.10623279598019508, 0.4809183794585733, 0.26019049604127387, 0.36650613340322613, 0.268064638353972, 0.46490932146695974, 0.5617047113643219, 0.44201263176803696, 0.3323630376527701, 0.8331032367492698, 0.8015684677669017, 0.46595092144039807, 0.5955309640997363, 0.26007884989944685, 0.7194686811315889, 0.30811886205676053, 0.8522887020961659, 0.3132264481445697, 0.6726763034568207, 0.09856858162047144, 0.33945564292040065, 0.7971380126789529, 0.6823496444374736, 0.7805126960825012, 0.7248826760081567]


Zdefiniowanie funckji dla listy i array

In [100]:
 def ArrayOperations():
   ar_min=ar.min()
   ar_max=ar.max()
   ar_sum=ar.sum()
   ar_prod=ar.prod()
   ar_mean=ar.mean()
   ar_std=ar.std()
   ar_var=ar.var()
   return {'min':ar_min,'max':ar_max,'sum':ar_sum,'prod':ar_prod,'mean':ar_mean,'std':ar_std,'var':ar_var}

 def ListOperations():
   li_min=min(li)
   li_max=max(li)
   li_sum=sum(li)
   li_prod=1
   for i in range(len(li)):
     li_prod*=li[i]
   li_mean=sum(li)/len(li)
   li_var_n=0
   for i in range(len(li)):
     li_var_n+=(li[i]-li_mean)**2
   li_var=li_var_n/len(li)
   li_std=li_var**(1/2) 
   return {'min':li_min,'max':li_max,'sum':li_sum,'prod':li_prod,'mean':li_mean,'std':li_std,'var':li_var}

print(ArrayOperations())
print(ListOperations())

{'min': 0.05941828193074239, 'max': 0.9141127920212525, 'sum': 13.334165170504603, 'prod': 5.173083728421613e-15, 'mean': 0.4444721723501534, 'std': 0.27808680753253767, 'var': 0.07733227252363864}
{'min': 0.09856858162047144, 'max': 0.8522887020961659, 'sum': 14.168946135290419, 'prod': 3.3935701835857985e-12, 'mean': 0.47229820450968063, 'std': 0.2200025041256234, 'var': 0.04840110182154494}


In [101]:
t_ar = timeit.timeit(ArrayOperations, number=1000)
t_li = timeit.timeit(ListOperations, number=1000)

print("Czas funkcji Array:",t_ar)
print("Czas funkcji List:",t_li)
if t_ar>t_li: print("Wniosek: Operacje na Liście w tym przypadku szybsze niż na Array")
else: print("Wniosek: Operacje na Array w tym przypadku szybsze niż na Liście")

Czas funkcji Array: 0.07241231500029244
Czas funkcji List: 0.008428747999460029
Wniosek: Operacje na Liście w tym przypadku szybsze niż na Array


Sprawdzenie mniej elementarnych obliczeń

In [102]:
#podniesienie do kwadratu każdego elementu
def x(): [i**2 for i in li] 
def y(): ar**2

t_ar = timeit.timeit(y, number=1000)
t_li = timeit.timeit(x, number=1000)

print("Czas funkcji Array:",t_ar)
print("Czas funkcji List:",t_li)
if t_ar>t_li: print("Wniosek: Operacje na Liście w tym przypadku szybsze niż na Array")
else: print("Wniosek: Operacje na Array w tym przypadku szybsze niż na Liście")

Czas funkcji Array: 0.0018691109999053879
Czas funkcji List: 0.002270047000820341
Wniosek: Operacje na Array w tym przypadku szybsze niż na Liście


Wybrane sposoby oracy z tablicami zdefiniowanymi w pakiecie numpy

In [104]:
x=np.random.random(100)
x.reshape(4,5,5) #zwraca zmienioną Array: 4 główne listy które zawierają po 5 pięcio elementowych list
print("x po reshape",x)
x.resize(4,5,5) #zmienioniaa Array: 4 główne listy które zawierają po 5 pięcio elementowych list
print("x po resize",x)

x po reshape [0.8173253  0.26936745 0.61124333 0.99911122 0.18542726 0.06075078
 0.15820463 0.95932167 0.47601087 0.92365176 0.99608573 0.28119595
 0.95044918 0.12606682 0.24357171 0.1744122  0.81993836 0.98561401
 0.94829449 0.91911891 0.72336203 0.88546519 0.46561932 0.12717181
 0.40351862 0.94332907 0.23850847 0.31040624 0.64233252 0.44373023
 0.4397209  0.71107238 0.11951529 0.52693493 0.24722197 0.03896452
 0.39294246 0.94595401 0.3393263  0.5727426  0.29035028 0.73610772
 0.5041758  0.54233037 0.82147756 0.64257751 0.07898339 0.0612463
 0.6402712  0.9629075  0.47189416 0.69108278 0.9697318  0.91644251
 0.50566171 0.08771687 0.61915275 0.23536599 0.44134671 0.32698469
 0.1947356  0.03293468 0.63605753 0.56534758 0.74294526 0.7876617
 0.85387685 0.74029454 0.21657524 0.23552167 0.87912876 0.45702144
 0.45438791 0.05261892 0.87999281 0.41782009 0.37055557 0.26087049
 0.1997548  0.64944841 0.59332936 0.82394625 0.9331672  0.12781042
 0.75534857 0.98266645 0.91838552 0.44267221 0.9160

In [105]:
print("Liczba wymiarów:",x.ndim)
print("Rozmiar tablicy:",x.shape)
print("Liczba elementów:",x.size)
print("Typ elementów:",x.dtype)
print("Rozmiar elementu w bajtach:",x.itemsize)

print(x.ravel()) #spłaszczenie Array'a

Liczba wymiarów: 3
Rozmiar tablicy: (4, 5, 5)
Liczba elementów: 100
Typ elementów: float64
Rozmiar elementu w bajtach: 8
[0.8173253  0.26936745 0.61124333 0.99911122 0.18542726 0.06075078
 0.15820463 0.95932167 0.47601087 0.92365176 0.99608573 0.28119595
 0.95044918 0.12606682 0.24357171 0.1744122  0.81993836 0.98561401
 0.94829449 0.91911891 0.72336203 0.88546519 0.46561932 0.12717181
 0.40351862 0.94332907 0.23850847 0.31040624 0.64233252 0.44373023
 0.4397209  0.71107238 0.11951529 0.52693493 0.24722197 0.03896452
 0.39294246 0.94595401 0.3393263  0.5727426  0.29035028 0.73610772
 0.5041758  0.54233037 0.82147756 0.64257751 0.07898339 0.0612463
 0.6402712  0.9629075  0.47189416 0.69108278 0.9697318  0.91644251
 0.50566171 0.08771687 0.61915275 0.23536599 0.44134671 0.32698469
 0.1947356  0.03293468 0.63605753 0.56534758 0.74294526 0.7876617
 0.85387685 0.74029454 0.21657524 0.23552167 0.87912876 0.45702144
 0.45438791 0.05261892 0.87999281 0.41782009 0.37055557 0.26087049
 0.1997548

In [106]:
s=(2,3,4)
print("Array zawierający tylko zera")
print(np.zeros(s))
print("Array zawierający tylko jedynki")
print(np.ones(s))
print("Array zawierający jedynki tylko na przekątnej")
print(np.eye(4))

Array zawierający tylko zera
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
Array zawierający tylko jedynki
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
Array zawierający jedynki tylko na przekątnej
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [107]:
print(np.arange(4,99,3)) #liczby od 4 do 99 co 3
print(np.linspace(0,100,11)) #podział odcinka [0,100] na 11 liczb, oddalonych od siebie równomiernie

[ 4  7 10 13 16 19 22 25 28 31 34 37 40 43 46 49 52 55 58 61 64 67 70 73
 76 79 82 85 88 91 94 97]
[  0.  10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]


In [108]:
x=np.random.random(16).reshape((4,4))
x
print(np.vstack((x,
                 [3.,4.,5.,6.]))) #dodanie kolejnego "wiersza"
print(np.hstack((x,
                 np.array([3.,4.,5.,6.]).reshape(4,1)))) #dodanie koeljnej "kolumny"

[[0.81326104 0.20059145 0.67401727 0.60990648]
 [0.6851108  0.51266716 0.92879586 0.03069156]
 [0.92500811 0.04635147 0.669117   0.25225427]
 [0.28027437 0.61285263 0.33592668 0.30264309]
 [3.         4.         5.         6.        ]]
[[0.81326104 0.20059145 0.67401727 0.60990648 3.        ]
 [0.6851108  0.51266716 0.92879586 0.03069156 4.        ]
 [0.92500811 0.04635147 0.669117   0.25225427 5.        ]
 [0.28027437 0.61285263 0.33592668 0.30264309 6.        ]]
